version: '3.2'

volumes:
  opt-splunk-etc:
  opt-splunk-var:

services:
  splunkuniversalforwarder:

    hostname: splunkuniversalforwarder
    #image: splunk/universalforwarder:7.0.3
    image: splunk/universalforwarder:6.5.2-monitor

    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_USER : root
    volumes:
      - opt-splunk-etc:/opt/splunk/etc
      - opt-splunk-var:/opt/splunk/var
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"