version: '3.2'
volumes:
      logs-syslog:

services:
    log-client:
      hostname: log-client
      build: './client'
      depends_on:
        - log-collector

    log-collector:
      build: './collector'
      volumes:
        - logs-syslog:/var/log/syslog-ng/logs-syslog

    splunk-forwarder:
      hostname: splunk-forwarder
   #   image: splunk/universalforwarder:6.5.2-monitor
      image: splunk/splunk:latest
      environment:
        SPLUNK_START_ARGS: --accept-license --answer-yes
        SPLUNK_USER: root
        SPLUNK_PASSWORD: changeme
      volumes:
      - logs-syslog:/opt/splunk/var/log/logs-syslog
      - ./forwarder/inputs.conf:/opt/splunk/etc/system/local/inputs.conf
      - ./forwarder/outputs.conf:/opt/splunk/etc/system/local/outputs.conf
      ports:
      - "8089:8089"
      - "9997:9997"
      depends_on:
      - log-collector
      - splunk-receiver

    splunk-receiver:
      hostname: my-splunk-indexer
      image : splunk/splunk:latest
      ports:
        - "8000:8000"
      env_file:
        - receiver/receiver.env
      volumes:
      - ./receiver/inputs.conf:/opt/splunk/etc/system/local/inputs.conf
      - ./receiver/indexes.conf:/opt/splunk/etc/system/local/indexes.conf


